################################################
###### Latent Dirichlet algorithm ##############
################################################

# There are two principles:
#1. Every document is a combination of multiple topics
#2. Every topic is a combination of multiple words

#install.packages("xxxxxxxxx")
library(xxxxxxxxxx) #new articles from American news agencies
data("AssociatedPress")

AssociatedPress

#calling the Latent Dirichlet Allocation algorithm
ap_lda <- xxxxxx(AssociatedPress, k=xxxx, control=list(seed=123))
ap_lda

#now we are looking for the per topic per word probabilities aka. beta
#beta - what is the probability that "this term" will be generated by "this topic"
library(tidytext)
ap_topics <- xxxxxxxxx(ap_lda, matrix=xxxxxxx)
ap_topics
library(ggplot2)
library(dplyr)
library(tidyr)

top_terms <- ap_topics %>%
              xxxxxxxx(topic) %>%
              xxxxxxx(10, xxxx) %>%
              ungroup() %>%
              xxxxxxx(topic, -beta)
top_terms

#lets plot the term frequencies by topic
top_terms %>%
  xxxxxxxxx(term=xxxxxxxx(term, beta)) %>%
  ggplot(aes(term, xxxxxxx, xxxxx = factor(topic))) +
  geom_col(xxxxxxx.xxxxxxxx=FALSE) +
  facet_wrap(~topic, xxxxxxx = "free") +
  xxxxxxxxxxxx()

#lets calculate the relative difference between the betas for words in topic 1
#and words in topic 2

beta_spread <- xxxxxx %>%
  mutate(topic=paste0("topic", topic)) %>%
  spread(xxxxxxx, xxxxx) %>%
  filter(topic1>xxxxxx | topic2 >xxxxxxx) %>%
  mutate(xxxxxxx = log2(topic2/topic1))

beta_spread

################################################
###### LDA per chapter based on Gutenber#########
################################################

library(gutenbergr)
titles <- c("Twenty Thousand Leagues under the Sea", "The War of the Worlds",
            "Pride and Prejudice", "Great Expectations")

books <- gutenberg_works(title %in% titles) %>%
  gutenberg_download(meta_fields = "title")

#devide into documents, each representing on e chapter
library(xxxxxxx)
reg <-xxxxxxxx(xxxxxxxxx, ignore_case=TRUE)
by_chapter <- books %>%
  group_by(title) %>%
  mutate(chapter=cumsum(str_detect(text,reg))) %>%
  ungroup() %>%
  filter(chapter>0) %>%
  unite(document, title, chapter)

#split into words
by_chapter_word <- by_chapter %>%
  unnest_tokens(word, text)

#find document-word counts
word_counts <- xxxxxxxxx %>%
  xxxxxxxxx(stop_words) %>%
  count(xxxxxxxx, xxxxxx, sort = TRUE) %>%
  ungroup()

print(word_counts)

chapters_dtm <- word_counts %>%
  xxxxxxxxxx(xxxxxxxx, word, n)

chapters_lda <- xxxxxxx(chapters_dtm,k=xxxxxx, control = list(seed=123))
chapters_lda

###############################################
#### Per documnet classification ##############
###############################################

chapters_gamma <- tidy(xxxxxxxx, matrix=xxxxxxx)
chapters_gamma 

chapters_gamma <- xxxxxxxx %>%
  xxxxxxxxx(document, c("title", "chapter"),sep = "_", convert=TRUE)

chapters_gamma

chapters_gamma %>%
  xxxxx(title=reorder(title, xxxxxxx*xxxxxxxx)) %>%
  ggplot(aes(factor(topic), gamma)) +
  xxxxxxxxxxxx()+
  facet_wrap(~title)

chapter_classifications <- xxxxxxxxxxxx %>%
  group_by(xxxxxxxxxxxx, xxxxxxxxxxx) %>%
  top_n(1, xxxxxxxxx) %>%
  xxxxxxxxxx()

chapter_classifications


